### GET /api/notes/:id
GET http://localhost:3010/api/notes

### DELETE /api/notes/:id
DELETE http://localhost:3010/api/notes/1

### POST /api/notes/
POST http://localhost:3010/api/notes 
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "content": "bar"
}